[package]
name = "jim"
description = "Profile based configuration wrapper for vim"
author = "cwlittle <cwlittle@utexas.edu>"
license = "MIT"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
